services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: ..
      target: dev
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    env_file:
      - path: ./dev/.env
      - path: ./dev/override.env
        required: false
    environment:
      DB_DSN: "mysql:host=mysql;port=3306;dbname=${MYSQL_DATABASE:-app}"
      DB_USER: "${MYSQL_USER:-app}"
      DB_PASSWORD: "${MYSQL_PASSWORD:-secret}"
      REDIS_DSN: "redis://redis:6379"
    ports:
      - "${DEV_PORT:-80}:80"
    volumes:
      - ../:/app
      - ../runtime:/app/runtime
      - caddy_data:/data
      - caddy_config:/config
    tty: true

